### ISSUE TITLE
CLI and  Inside Python Code can't load model success.

### ISSUE THREAD

**Issue by sev777** [Riccorl/transformer-srl#13]
When load model : "srl_bert_base_conll2012.tar.gz" , the error is :

```
RuntimeError: Error loading state dict for TransformerSrlSpan
        Missing keys: ['transformer.embeddings.position_ids']
        Unexpected keys: []
```

**Comment by rahmanidashti** [comment]
It also happens to me. Did you find a solution for that?

**Comment by sev777** [comment]
> It also happens to me. Did you find a solution for that?

No, I didn't find anything for this, and I find  the code in file "model.py" didn't use LSTM? But the paper [Shi et al, 2019](https://arxiv.org/abs/1904.05255)  did.

**Comment by sev777** [comment]
> It also happens to me. Did you find a solution for that?

No, I didn't find anything for this. And the code in 'model.py' didn't use LSTM? But the [paper](https://arxiv.org/abs/1904.05255) did, was it be used elsewhere?

**Comment by rahmanidashti** [comment]
I solved it using:

`pip install allennlp==2.1.0 allennlp-models==2.1.0` and:
`https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz`
