### ISSUE TITLE
Need a simple how-to-use guide

### ISSUE THREAD

**Issue by therealhieu** [Riccorl/transformer-srl#4]
Your work is awesome!
Can you guide me how to use transformer-srl as a standalone for a single sentence?

**Comment by Riccorl** [comment]
I think you can predict like this

```python
from transformer_srl import dataset_readers, models, predictors

predictor = predictors.SrlTransformersPredictor.from_path(model_path, "transformer_srl")
predictor.predict(
  sentence="Did Uriah honestly think he could beat the game in under three hours?"
)

```

Let me know if it works :)

**Comment by KTRosenberg** [comment]
Where and what is the model file that I should point to with "model_path?"  I can't figure out what to pass there. If possible, please show a complete example.

**Comment by Riccorl** [comment]
> Where and what is the model file that I should point to with "model_path?" I can't figure out what to pass there. If possible, please show a complete example.

`model_path` should point to the pretrained model in your file system. I updated the README with the instructions and the download link to it .

**Comment by KTRosenberg** [comment]
Thanks!
