### ISSUE TITLE
Cannot download model from drop-box

### ISSUE THREAD

**Issue by MausamGaurav** [Riccorl/transformer-srl#8]
Could the pre-trained model be uploaded to another location please. Dropbox and google drive etc. are blocked due to corporate policy. Or could the url to the specific original model from Allen NLP be provided. Then you may just upload the extra files from the core models from Allen NLP on github.

**Comment by Riccorl** [comment]
The weights of the original model don't work with my implementation, for that you can simply use the AllenNLP code.

Which provider will be good for you?

**Comment by MausamGaurav** [comment]
Hey Riccardo, thanks for taking a look. You can upload to GitHub itself using the large file storage option - https://git-lfs.github.com/. I believe this would work well for other users as well.

**Comment by Riccorl** [comment]
I don't have enough space on GitHub to upload such large model, unfortunately. Maybe you can download it from outside your corp network and upload in a repo?

**Comment by MausamGaurav** [comment]
Hi Riccardo, It's fine. I don't need it anymore, as the AllenNLP version is working for me. The AllenNLP version had an issue to work offline, but the issue has been resolved now. So all good for now.
